name: ci

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      -
        name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/ppc64le
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:0.2.4
